flyway.url=${FLYWAY_URL}
flyway.user=${FLYWAY_USER}
flyway.password=${FLYWAY_PASSWORD}
flyway.locations=filesystem:./sql
flyway.connectRetries=10
flyway.validateOnMigrate=true
flyway.baselineOnMigrate=true
